language: csharp
solution: TicTacToe.sln
install:
  - nuget restore TicTacToe.sln
  - nuget install xunit.runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TicTacToe.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./TicTacToeTests/bin/Release/TicTacToeTests.dll