language: csharp
solution: TicTacToe.sln
install:
  - mono paket.exe add nuget Xunit [verison 2.1.0] 
  - mono paket.exe install
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - mv ./paket-files/tcmcgee/TicTacToe.Core/TicTacToe.Core.1.0.0.nupkg ./paket-files/tcmcgee/TicTacToe.Core/TicTacToe.Core.1.0.0.zip 
  - mkdir ./packages/TicTacToe.Core.1.0.0
  - unzip ./paket-files/tcmcgee/TicTacToe.Core/TicTacToe.Core.1.0.0.zip -d ./packages/TicTacToe.Core.1.0.0 
  - xbuild /p:Configuration=Release TicTacToe.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./TicTacToeTests/bin/Release/TicTacToeTests.dll -noappdomain
