language: csharp
solution: TicTacToe.sln
install:
  - nuget restore TicTacToe.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TicTacToe.sln
  - cd TicTacToeTests/bin/Release
  - ls
  - cd ..
  - cd ..
  - cd ..
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TicTacToeTests/bin/Release/TicTacToeTests.dll
