language: csharp
solution: TicTacToe.sln
install:
  - nuget restore TicTacToe.sln
  - nuget install xunit.runners -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TicTacToe.sln
  - mono ./testrunner/xunit.runners.2.1.0/tools/xunit.console.clr4.exe ./TicTacToeTests/bin/Release/TicTacToeTests.dll
