language: csharp
mono:
  - latest
install:
  - nuget restore TicTacToe.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TicTacToe.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TicTacToe.Tests/bin/Release/TicTacToe.Tests.dll
